### ISSUE TITLE
Occasional `UnhandledPromiseRejectionWarning` with overlay disabled

### ISSUE THREAD

**Issue by gonX** [SnosMe/awakened-poe-trade#1247]
Error from console:
```
(node:4320) UnhandledPromiseRejectionWarning: Error: You are using the library in tracking mode
    at OverlayControllerGlobal.activateOverlay (/tmp/.mount_AwakenFAe7cI/resources/app.asar/node_modules/electron-overlay-window/dist/index.js:184:19)
    at qw.assertOverlayActive (/tmp/.mount_AwakenFAe7cI/resources/app.asar/main.js:467:1871)
    at qw.toggleActiveState (/tmp/.mount_AwakenFAe7cI/resources/app.asar/main.js:467:2156)
    at Function.<anonymous> (/tmp/.mount_AwakenFAe7cI/resources/app.asar/main.js:469:13937)
    at Object.showErrorBox (node:electron/js2c/browser_init:2:21358)
    at node:electron/js2c/browser_init:2:120112
```

APT version `3.23.10003`, though I don't think it hasn't been happening since the argument was introduced.

I use the AppImage on Linux with the `--no-overlay` argument

While I don't have good steps to reproduce the error, it seems to happen when using the pricing shortcuts (ctrl+alt+D, etc) - or at least, my APT becomes unresponsive until I close the error message (which is occluded by my game on my configuration).

**Comment by gonX** [comment]
Oh, looks like this is a duplicate of #993
