### ISSUE TITLE
3.17 latest-mac.yml

### ISSUE THREAD

**Issue by italianfrost** [SnosMe/awakened-poe-trade#583]
I have installed 3.17 for Mac, from this link https://www.pathofexile.com/forum/view-thread/3129523/page/1 and followed the instructions however in researching from logs, it looks to be missing a file "latest-mac.yml".  Any help on correcting the issue would be great.

When I do launch it I get stuck in granting security & privacy permissions.  I have toggled it on and off at least 10 times.

error [etc]: Error: Error: Cannot find latest-mac.yml in the latest release artifacts (https://github.com/SnosMe/awakened-poe-trade/releases/download/v3.17.10004/latest-mac.yml): HttpError: 404 
"method: GET url: https://github.com/SnosMe/awakened-poe-trade/releases/download/v3.17.10004/latest-mac.yml\n\nPlease double check that your authentication token is correct. Due to security reasons, actual status maybe not reported, but 404.\n"
Headers: {
  "server": "GitHub.com",
  "date": "Wed, 30 Mar 2022 17:29:08 GMT",
  "content-type": "text/plain; charset=utf-8",
  "vary": "X-PJAX, X-PJAX-Container, Accept-Encoding, Accept, X-Requested-With",
  "permissions-policy": "interest-cohort=()",
  "cache-control": "no-cache",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "x-frame-options": "deny",
  "x-content-type-options": "nosniff",
  "x-xss-protection": "0",
  "referrer-policy": "no-referrer-when-downgrade",
  "expect-ct": "max-age=2592000, report-uri=\"https://api.github.com/_private/browser/errors\"",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-encoding": "gzip",
  "content-length": "29",
  "x-github-request-id": "E91F:7FC1:2643CE:4267B7:62449382"
}
    at d (/Applications/Awakened PoE Trade.app/Contents/Resources/app.asar/background.js:2:149909)
    at o.handleResponse (/Applications/Awakened PoE Trade.app/Contents/Resources/app.asar/background.js:2:151746)
    at ClientRequest.<anonymous> (/Applications/Awakened PoE Trade.app/Contents/Resources/app.asar/background.js:2:151209)
    at ClientRequest.emit (events.js:376:20)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6816)
    at SimpleURLLoaderWrapper.emit (events.js:376:20)
    at Object.t.newError (/Applications/Awakened PoE Trade.app/Contents/Resources/app.asar/background.js:2:3769)
    at t.GitHubProvider.getLatestVersion (/Applications/Awakened PoE Trade.app/Contents/Resources/app.asar/background.js:2:165329)
    at async u.getUpdateInfoAndProvider (/Applications/Awakened PoE Trade.app/Contents/Resources/app.asar/background.js:2:55440)
    at async u.doCheckForUpdates (/Applications/Awakened PoE Trade.app/Contents/Resources/app.asar/background.js:2:55726)
    at async Ee (/Applications/Awakened PoE Trade.app/Contents/Resources/app.asar/background.js:2:405282) {}

**Comment by SnosMe** [comment]
It's indeed missing because I don't release macOS version.
Presence of this error should not affect the work of app.

**Comment by italianfrost** [comment]
It is impacting, the app keeps crashing looking for it.  But also keeps asking for permissions, I have granted permissions numerous times.  Any suggestion on how to correct the permission request even though it has it?
