### ISSUE TITLE
Crashing on startup after installing 2.11.0.0

### ISSUE THREAD

**Issue by luc4sdreyer** [SnosMe/awakened-poe-trade#605]
Crashing on startup after installing latest version a few minutes ago (2.11.0.0 I think).
```
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
ReferenceError: Cannot access 'q' before initialization
    at E:\Users\xxx\AppData\Local\Programs\Awakened PoE Trade\resources\app.asar\background.js:2:520094
    at Module.<anonymous> (E:\Users\xxx\AppData\Local\Programs\Awakened PoE Trade\resources\app.asar\background.js:2:522607)
    at r (E:\Users\xxx\AppData\Local\Programs\Awakened PoE Trade\resources\app.asar\background.js:2:110)
    at Object.<anonymous> (E:\Users\xxx\AppData\Local\Programs\Awakened PoE Trade\resources\app.asar\background.js:2:274978)
    at r (E:\Users\xxx\AppData\Local\Programs\Awakened PoE Trade\resources\app.asar\background.js:2:110)
    at E:\Users\xxx\AppData\Local\Programs\Awakened PoE Trade\resources\app.asar\background.js:2:902
    at Object.<anonymous> (E:\Users\xxx\AppData\Local\Programs\Awakened PoE Trade\resources\app.asar\background.js:2:913)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)

[OK]
```

**Comment by SnosMe** [comment]
This is some ancient version of app. Update to latest?

**Comment by luc4sdreyer** [comment]
OK, looks like a shortcut got replaced and I started an old version.

Current version is running but can't search due to the new trade engine. Is there a ticket for that?

**Comment by SnosMe** [comment]
Nope, but I'm aware
